#服务器端口
server:
  port: 9003

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

# xxl-job
xxl:
  job:
    admin:
      addresses: http://39.106.8.177:9005/xxl-job-admin
    executor:
      appname: "jgyhw-order-dev"
      ip:
      port: 19003
      logpath: D:\applogs\xxl-job\jgyhw-order-dev
      logretentiondays: 10
    accessToken:
